### ISSUE TITLE
도메인 변경 및 조직 이름 변경 논의

### ISSUE THREAD

**Issue by pulp-pixel** [envybros/.com#16]
"bros"는 우리 하는 모든 일을 뜻하는 거 아닌가?
"academy"가 맞지 않을까. 

만약 아카데미 작업 다 한다해도, 저 사이트를 같이 쓸 수도 있지 않을까?

카테고리를 조금 더 알기 쉽게 분류할 수 있다면?
그렇다면 저기 html 구조를 살짝 손봐야해

**Comment by pablo-stelsi** [comment]
굳이 할 필요 없어보임

우선 카테고리는 손 봐야하는 건 맞다.
