### ISSUE TITLE
다크 및 라이트 테마 색상 팔레트 수정

### ISSUE THREAD

**Issue by pulp-pixel** [envybros/.com#18]
지금 색깔 심히 아쉬움
특히 prompt 색상 무슨 일이냐..

대신 소스 코드 부분은 참 예뻐서 보기 좋아서 그냥 둬도 될듯
코드 라인과 복사까지 들어있는 훌륭한 부문. 

색상들만 변경해보자.

**Comment by pulp-pixel** [comment]
하는 김에 라이센스 링크 저거 한글 링크로 바꿔야 할 것 같다

**Comment by pablo-stelsi** [comment]
cpp 카테고리만 따로 볼 수 있게는 못하나?
링크도 post/0.1-intro ~~ 이런 식이 아니라
cpp/0.1-intro~ 이런 식으로

**Comment by pablo-stelsi** [comment]
이 작업 우선 진행
